In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
491858,Senior Data Engineer,Sr. Data Engineer (Hybrid),"Longview, TX",via SaluteMyJob,Full-time and Part-time,False,"California, United States",2023-11-27 11:10:23,False,True,United States,year,173500.0,NaN,Capital One,"['scala', 'nosql', 'python', 'sql', 'java', 'm...","{'cloud': ['aws', 'azure', 'redshift', 'snowfl..."
154095,Cloud Engineer,Service Engineer,"Amman, Jordan",via Trabajo.org,Full-time,False,Jordan,2023-08-10 09:06:11,False,False,Jordan,NaN,NaN,NaN,Doroob,['excel'],{'analyst_tools': ['excel']}
244786,Data Engineer,Data Engineer SAP Reporting,"Salzburg, Austria",via Jobs Trabajo.org,Full-time,False,Austria,2023-12-17 07:16:08,True,False,Austria,NaN,NaN,NaN,Hays,"['sap', 'jira', 'confluence']","{'analyst_tools': ['sap'], 'async': ['jira', '..."
729980,Data Scientist,Data Scientist Intern,"Austin, TX",via Trabajo.org,Full-time,False,"Texas, United States",2023-03-26 21:04:50,False,False,United States,NaN,NaN,NaN,6sense,"['sql', 'python']","{'programming': ['sql', 'python']}"
493923,Data Engineer,ESG data engineer (m/f/d),"Munich, Germany",via LinkedIn,Full-time,False,Germany,2023-10-03 11:15:32,True,False,Germany,NaN,NaN,NaN,Allianz Commercial,"['python', 'sql', 'java', 'pyspark', 'flow']","{'libraries': ['pyspark'], 'other': ['flow'], ..."

Index Attributes : 
index.name  name of the index
index.dtype data type of the index

In [3]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [4]:
df.index.dtype

dtype('int64')

In [5]:
df.index.name 
#has no name

In [6]:
df.index.name = 'job_index' # make a name 
df.index.name

'job_index'

In [7]:
df.sample(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
472211,Senior Data Engineer,Senior Big Data Engineer,India,via LinkedIn,Full-time,False,India,2023-08-26 14:11:33,False,False,India,NaN,NaN,NaN,Virtusa,"['java', 'javascript', 'bash', 'aws', 'redshif...","{'cloud': ['aws', 'redshift'], 'libraries': ['..."
661527,Senior Data Analyst,Senior Data Analyst - Department of Urology,"New York, NY",via LinkedIn,Full-time,False,"New York, United States",2023-07-27 10:00:05,False,True,United States,NaN,NaN,NaN,NYU Langone Health,"['go', 'sql', 'python', 'postgresql', 'oracle']","{'cloud': ['oracle'], 'databases': ['postgresq..."
505316,Data Engineer,Data Manager - Data Engineer H/F,"Tours, France",via LinkedIn,Full-time,False,France,2023-07-17 12:07:33,False,False,France,NaN,NaN,NaN,Avanci - MV Group,NaN,NaN

In [20]:
median_pivot = df.pivot_table ( values= 'salary_year_avg', index ='job_title_short', aggfunc= 'median')
median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0

In [22]:
median_pivot_index= median_pivot.index.name
median_pivot_index

'job_title_short'

In [23]:
median_pivot_type = median_pivot.index.dtype
median_pivot_type

Reset_index()

In [12]:
df_mac= df[df['job_country'] == "Morocco"]
df_mac.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
1836,Data Analyst,Data Analyst,Morocco,via تنقيب,Full-time,False,Morocco,2023-10-10 13:30:18,False,False,Morocco,NaN,NaN,NaN,Confidentiel,"['sql', 'python', 'r', 'php', 'java', 'postgre...","{'analyst_tools': ['tableau'], 'databases': ['..."
1991,Data Engineer,Data Engineer (H/F),"Rabat, Morocco",via LinkedIn,Full-time,False,Morocco,2023-11-30 13:19:30,False,False,Morocco,NaN,NaN,NaN,Orange Business,"['sql', 'powershell', 'oracle', 'hadoop', 'lin...","{'async': ['jira', 'confluence'], 'cloud': ['o..."
2109,Data Scientist,Data Scientist,"Tangier, Morocco",via ReKrute.com,Full-time,False,Morocco,2023-12-20 13:16:44,False,False,Morocco,NaN,NaN,NaN,Altados,"['python', 'r', 'sql', 'elasticsearch', 'spark...","{'databases': ['elasticsearch'], 'libraries': ..."
2225,Data Scientist,Data Scientist / Professeur en Data science,Morocco,via Nature,Full-time,False,Morocco,2023-10-19 14:10:18,False,False,Morocco,NaN,NaN,NaN,Mohammed VI Polytechnic University,"['r', 'python', 'matlab']","{'programming': ['r', 'python', 'matlab']}"
2728,Data Scientist,Data scientist,"Rabat, Morocco",via SmartRecruiters Job Search,Full-time,False,Morocco,2023-11-24 13:18:28,False,False,Morocco,NaN,NaN,NaN,ALTEN,"['r', 'sql', 'postgresql']","{'databases': ['postgresql'], 'programming': [..."

In [13]:
df_mac.index

Index([  1836,   1991,   2109,   2225,   2728,   3363,   3835,   3839,   3842,
         4071,
       ...
       768095, 771636, 772318, 772392, 772993, 773179, 779096, 780466, 782860,
       785071],
      dtype='int64', name='job_index', length=1214)

In [16]:
df_mac.reset_index(inplace  =True)
df_mac.head(3)

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,1836,Data Analyst,Data Analyst,Morocco,via تنقيب,Full-time,False,Morocco,2023-10-10 13:30:18,False,False,Morocco,NaN,NaN,NaN,Confidentiel,"['sql', 'python', 'r', 'php', 'java', 'postgre...","{'analyst_tools': ['tableau'], 'databases': ['..."
1,1991,Data Engineer,Data Engineer (H/F),"Rabat, Morocco",via LinkedIn,Full-time,False,Morocco,2023-11-30 13:19:30,False,False,Morocco,NaN,NaN,NaN,Orange Business,"['sql', 'powershell', 'oracle', 'hadoop', 'lin...","{'async': ['jira', 'confluence'], 'cloud': ['o..."
2,2109,Data Scientist,Data Scientist,"Tangier, Morocco",via ReKrute.com,Full-time,False,Morocco,2023-12-20 13:16:44,False,False,Morocco,NaN,NaN,NaN,Altados,"['python', 'r', 'sql', 'elasticsearch', 'spark...","{'databases': ['elasticsearch'], 'libraries': ..."

In [24]:
median_pivot.reset_index(inplace = True)
median_pivot

             job_title_short  salary_year_avg
0           Business Analyst          85000.0
1             Cloud Engineer          90000.0
2               Data Analyst          90000.0
3              Data Engineer         125000.0
4             Data Scientist         127500.0
5  Machine Learning Engineer         106415.0
6        Senior Data Analyst         111175.0
7       Senior Data Engineer         147500.0
8      Senior Data Scientist         155500.0
9          Software Engineer          99150.0

Set_index()
back to job_index as our main index

In [17]:
df_mac.set_index('job_index',inplace = True)
df_mac.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
1836,Data Analyst,Data Analyst,Morocco,via تنقيب,Full-time,False,Morocco,2023-10-10 13:30:18,False,False,Morocco,NaN,NaN,NaN,Confidentiel,"['sql', 'python', 'r', 'php', 'java', 'postgre...","{'analyst_tools': ['tableau'], 'databases': ['..."
1991,Data Engineer,Data Engineer (H/F),"Rabat, Morocco",via LinkedIn,Full-time,False,Morocco,2023-11-30 13:19:30,False,False,Morocco,NaN,NaN,NaN,Orange Business,"['sql', 'powershell', 'oracle', 'hadoop', 'lin...","{'async': ['jira', 'confluence'], 'cloud': ['o..."
2109,Data Scientist,Data Scientist,"Tangier, Morocco",via ReKrute.com,Full-time,False,Morocco,2023-12-20 13:16:44,False,False,Morocco,NaN,NaN,NaN,Altados,"['python', 'r', 'sql', 'elasticsearch', 'spark...","{'databases': ['elasticsearch'], 'libraries': ..."

In [25]:
median_pivot.set_index('job_title_short', inplace= True)
median_pivot

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0