In [89]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
# Create copy of Data
df_orgl = df.copy()

In [90]:
# Use double brackets [[]] so df_salary remains a DataFrame
df_salary = df_orgl [pd.notna(df_orgl['salary_year_avg'])][['salary_year_avg']]
df_salary

        salary_year_avg
28             109500.0
77             140000.0
92             120000.0
100            228222.0
109             89000.0
...                 ...
785624         139216.0
785641         150000.0
785648         221875.0
785682         157500.0
785692         157500.0

[22003 rows x 1 columns]

In [91]:
# Directly calculate the inflated salary column
df_salary['salary_year_inflated'] = df_salary['salary_year_avg']*1.03
# View columns
df_salary[['salary_year_inflated', 'salary_year_avg']]

        salary_year_inflated  salary_year_avg
28                 112785.00         109500.0
77                 144200.00         140000.0
92                 123600.00         120000.0
100                235068.66         228222.0
109                 91670.00          89000.0
...                      ...              ...
785624             143392.48         139216.0
785641             154500.00         150000.0
785648             228531.25         221875.0
785682             162225.00         157500.0
785692             162225.00         157500.0

[22003 rows x 2 columns]

Using Function Apply()

In [ ]:
#Calculate projected salaries next year,apply by column.

df_salary = df_orgl[df_orgl['salary_year_avg'].notna()][['salary_year_avg']].copy()

#Define the function 
def projected_salary(salary):
    return salary * 1.03  #using an assumed rate of 3.0% for all roles
# create column salary_year_inflated 
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)
# View columns
df_salary[['salary_year_inflated', 'salary_year_avg']]

        salary_year_inflated  salary_year_avg
28                 112785.00         109500.0
77                 144200.00         140000.0
92                 123600.00         120000.0
100                235068.66         228222.0
109                 91670.00          89000.0
...                      ...              ...
785624             143392.48         139216.0
785641             154500.00         150000.0
785648             228531.25         221875.0
785682             162225.00         157500.0
785692             162225.00         157500.0

[22003 rows x 2 columns]

Calculate projected salaries next year, but: apply by rows

In [93]:
df_salary = df_orgl [pd.notna(df_orgl['salary_year_avg'])][['salary_year_avg', 'job_title_short']].copy()

def projected_salary(row) : 
    if 'Senior' in row['job_title_short'] : 
      return row['salary_year_avg'] *1.05 ##For senior roles (e.g., Senior Data Analysts), assume the rate is 5%
    else :
      return row['salary_year_avg'] *1.03  #For all other roles, assume rate is 3%
df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis =1)
df_salary[['job_title_short','salary_year_inflated', 'salary_year_avg' , ]]

       job_title_short  salary_year_inflated  salary_year_avg
28      Data Scientist             112785.00         109500.0
77       Data Engineer             144200.00         140000.0
92       Data Engineer             123600.00         120000.0
100     Data Scientist             235068.66         228222.0
109       Data Analyst              91670.00          89000.0
...                ...                   ...              ...
785624   Data Engineer             143392.48         139216.0
785641   Data Engineer             154500.00         150000.0
785648  Data Scientist             228531.25         221875.0
785682  Data Scientist             162225.00         157500.0
785692  Data Scientist             162225.00         157500.0

[22003 rows x 3 columns]

In [94]:
# using Apply & Lambda 
df_salary['salary_year_inflated']= df_salary['salary_year_avg'].apply(lambda salary : salary *1.3)
df_salary[['salary_year_inflated', 'salary_year_avg']]

        salary_year_inflated  salary_year_avg
28                  142350.0         109500.0
77                  182000.0         140000.0
92                  156000.0         120000.0
100                 296688.6         228222.0
109                 115700.0          89000.0
...                      ...              ...
785624              180980.8         139216.0
785641              195000.0         150000.0
785648              288437.5         221875.0
785682              204750.0         157500.0
785692              204750.0         157500.0

[22003 rows x 2 columns]

In [95]:
df_salary['salary_year_inflated'] = df_salary.apply(lambda row : row['salary_year_avg'] *1.05  if 'Senior' in row['job_title_short'] else row['salary_year_avg'] *1.03 , axis = 1 )

df_salary[['job_title_short','salary_year_inflated', 'salary_year_avg' , ]]

       job_title_short  salary_year_inflated  salary_year_avg
28      Data Scientist             112785.00         109500.0
77       Data Engineer             144200.00         140000.0
92       Data Engineer             123600.00         120000.0
100     Data Scientist             235068.66         228222.0
109       Data Analyst              91670.00          89000.0
...                ...                   ...              ...
785624   Data Engineer             143392.48         139216.0
785641   Data Engineer             154500.00         150000.0
785648  Data Scientist             228531.25         221875.0
785682  Data Scientist             162225.00         157500.0
785692  Data Scientist             162225.00         157500.0

[22003 rows x 3 columns]

In [96]:
type(df['job_skills'][1])

str

In [97]:
# convert str to list by using literal_eval() function
import ast
ast.literal_eval(df['job_skills'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [98]:
type(ast.literal_eval(df['job_skills'][1]))

list

In [99]:
# For the whole serie by using apply and lambda
df['job_skills'] = df['job_skills'].apply(lambda skill_list : ast.literal_eval(skill_list)  if pd.notna(skill_list) else skill_list)

In [100]:
type(df['job_skills'][1])

list